<?php
// $Id$
/**
 * @file
 * TestVCS backend for Version Control API -
 * Helper for testing Version Control core
 */

/**
 * Implementation of hook_versioncontrol_backends().
 */
function versioncontrol_test_versioncontrol_backends() {
  return array(
    'test' => new VersioncontrolTestBackend()
  );
}

/**
 * Implementation of hook_autoload_info().
 */
function versioncontrol_test_autoload_info() {
  return array(
    'VersioncontrolTestAccount' => array(
      'file' => 'versioncontrol_test.inc',
    ),
    'VersioncontrolTestBackend' => array(
      'file' => 'versioncontrol_test.inc',
    ),
    'VersioncontrolTestItem' => array(
      'file' => 'versioncontrol_test.inc',
    ),
    'VersioncontrolTestOperation' => array(
      'file' => 'versioncontrol_test.inc',
    ),
    'VersioncontrolTestRepository' => array(
      'file' => 'versioncontrol_test.inc',
    ),
  );
}
